.TH _PRINTF 808 "October 2018" "0.1.0" "custom _printf man page"
.SH NAME
_printf \- custom printf function that prints any string with additional format operators
.SH SYNOPSIS
.B _printf.c
( const char * format,
.IR {parameters,
.IR ...}
)
.LP
.SH DESCRIPTION
Printf stands for print formatting. Our _printf provides identical functionality to the one in the standard library.
.br
This program will take strings, characters, numbers, etc. and print them along with certain (if any) formatting operations.
.br
.\"
.\" USAGE
.\"
.SH EXAMPLES
.TP
.ir FunctionCall: _printf("This is an %s.\\n", "example");
.TP
Result: This is an example.$ (The $ signifies an end of line character and therefore represents a new line being printed there.
.br
.TP
Variable Initialization: int n = 50;
.br
.TP
Function Call: _printf("This is the %dth example.\\n", n);
.br
.TP
Result: This is the 50th example.$
.SH
